import {
  ChartData,
  commentMatrixDataType,
  DebitCreditNoteDataType,
  DownloadSLADataType,
  FinancialBidDataType,
  GlobalAccessFilterData,
  LineItemDataType,
  PricingSheetDataType,
  ReportItem,
  ServiceInventoryCDataType,
  ServiceInventoryLDataType,
  serviceTypeDataType,
  siteDataType,
  StateData,
  StateMasterDataType,
} from "../types/Data";

export const globalAccessFilterData: GlobalAccessFilterData[] = [
  {
    id: 1,
    label: "Invoice",
    value: "invoice",
    roleNames: [
      "finance user",
      "invoicing approver",
      "finance manager",
      "admin",
    ],
  },
  {
    id: 2,
    label: "Debit & Credit Note",
    value: "debit-credit-note",
    roleNames: ["admin", "debit-credit-note"],
  },
  {
    id: 3,
    label: "Service Level Agreement",
    value: "service-level-agreement",
    roleNames: ["admin", "service-level-agreement"],
  },
  {
    id: 4,
    label: "customer",
    value: "customer",
    roleNames: ["customer"],
  },
  {
    id: 5,
    label: "Program Manager",
    value: "program manager",
    roleNames: ["program manager"],
  },
  {
    id: 5,
    label: "Ops Team ",
    value: "ops team",
    roleNames: ["ops team"],
  },
  {
    id: 6,
    label: "Admin",
    value: "admin",
    roleNames: ["admin"],
  },
];

export const chartData: ChartData[] = [
  {
    notesType: [],
    accessType: "invoice",
    month: "April",
    approvedInvoice: 73,
    rejectInvoice: 43,
    pendingInvoice: 45,
  },
  {
    notesType: [],
    accessType: "invoice",
    month: "May",
    approvedInvoice: 29,
    rejectInvoice: 10,
    pendingInvoice: 45,
  },
  {
    notesType: [],
    accessType: "invoice",
    month: "June",
    approvedInvoice: 24,
    rejectInvoice: 33,
    pendingInvoice: 43,
  },
  {
    notesType: [],
    accessType: "invoice",
    month: "July",
    approvedInvoice: 45,
    rejectInvoice: 43,
    pendingInvoice: 24,
  },
  {
    notesType: [],
    accessType: "invoice",
    month: "August",
    approvedInvoice: 45,
    rejectInvoice: 10,
    pendingInvoice: 56,
  },
  {
    notesType: [],
    accessType: "invoice",
    month: "September",
    approvedInvoice: 64,
    rejectInvoice: 45,
    pendingInvoice: 15,
  },
  {
    notesType: ["Debit"],
    accessType: "debit-credit-note",
    month: "April",
    approvedInvoice: 34,
    rejectInvoice: 19,
    pendingInvoice: 57,
  },
  {
    notesType: ["Debit"],
    accessType: "debit-credit-note",
    month: "May",
    approvedInvoice: 12,
    rejectInvoice: 10,
    pendingInvoice: 46,
  },
  {
    notesType: ["Debit"],
    accessType: "debit-credit-note",
    month: "June",
    approvedInvoice: 60,
    rejectInvoice: 10,
    pendingInvoice: 65,
  },
  {
    notesType: ["Debit"],
    accessType: "debit-credit-note",
    month: "July",
    approvedInvoice: 58,
    rejectInvoice: 56,
    pendingInvoice: 56,
  },
  {
    notesType: ["Debit"],
    accessType: "debit-credit-note",
    month: "August",
    approvedInvoice: 40,
    rejectInvoice: 67,
    pendingInvoice: 34,
  },
  {
    notesType: ["Debit"],
    accessType: "debit-credit-note",
    month: "September",
    approvedInvoice: 50,
    rejectInvoice: 67,
    pendingInvoice: 43,
  },
  {
    notesType: ["Credit"],
    accessType: "debit-credit-note",
    month: "April",
    approvedInvoice: 3,
    rejectInvoice: 19,
    pendingInvoice: 2,
  },
  {
    notesType: ["Credit"],
    accessType: "debit-credit-note",
    month: "May",
    approvedInvoice: 4,
    rejectInvoice: 5,
    pendingInvoice: 7,
  },
  {
    notesType: ["Credit"],
    accessType: "debit-credit-note",
    month: "June",
    approvedInvoice: 3,
    rejectInvoice: 10,
    pendingInvoice: 65,
  },
  {
    notesType: ["Credit"],
    accessType: "debit-credit-note",
    month: "July",
    approvedInvoice: 58,
    rejectInvoice: 20,
    pendingInvoice: 9,
  },
  {
    notesType: ["Credit"],
    accessType: "debit-credit-note",
    month: "August",
    approvedInvoice: 40,
    rejectInvoice: 20,
    pendingInvoice: 56,
  },
  {
    notesType: ["Credit"],
    accessType: "debit-credit-note",
    month: "September",
    approvedInvoice: 10,
    rejectInvoice: 60,
    pendingInvoice: 20,
  },
  {
    notesType: [],
    accessType: "service-level-agreement",
    month: "April",
    approvedInvoice: 654,
    rejectInvoice: 190,
    pendingInvoice: 60,
  },
  {
    notesType: [],
    accessType: "service-level-agreement",
    month: "May",
    approvedInvoice: 564,
    rejectInvoice: 130,
    pendingInvoice: 80,
  },
  {
    notesType: [],
    accessType: "service-level-agreement",
    month: "June",
    approvedInvoice: 566,
    rejectInvoice: 140,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "service-level-agreement",
    month: "July",
    approvedInvoice: 766,
    rejectInvoice: 140,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "service-level-agreement",
    month: "August",
    approvedInvoice: 765,
    rejectInvoice: 46,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "service-level-agreement",
    month: "September",
    approvedInvoice: 67,
    rejectInvoice: 456,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "customer",
    month: "April",
    approvedInvoice: 654,
    rejectInvoice: 190,
    pendingInvoice: 60,
  },
  {
    notesType: [],
    accessType: "customer",
    month: "May",
    approvedInvoice: 564,
    rejectInvoice: 130,
    pendingInvoice: 80,
  },
  {
    notesType: [],
    accessType: "customer",
    month: "June",
    approvedInvoice: 566,
    rejectInvoice: 140,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "customer",
    month: "July",
    approvedInvoice: 766,
    rejectInvoice: 140,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "customer",
    month: "August",
    approvedInvoice: 765,
    rejectInvoice: 46,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "customer",
    month: "September",
    approvedInvoice: 67,
    rejectInvoice: 456,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "program manager",
    month: "April",
    approvedInvoice: 654,
    rejectInvoice: 190,
    pendingInvoice: 60,
  },
  {
    notesType: [],
    accessType: "program manager",
    month: "May",
    approvedInvoice: 564,
    rejectInvoice: 130,
    pendingInvoice: 80,
  },
  {
    notesType: [],
    accessType: "program manager",
    month: "June",
    approvedInvoice: 566,
    rejectInvoice: 140,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "program manager",
    month: "July",
    approvedInvoice: 766,
    rejectInvoice: 140,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "program manager",
    month: "August",
    approvedInvoice: 765,
    rejectInvoice: 46,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "program manager",
    month: "September",
    approvedInvoice: 67,
    rejectInvoice: 456,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "ops team",
    month: "April",
    approvedInvoice: 654,
    rejectInvoice: 190,
    pendingInvoice: 60,
  },
  {
    notesType: [],
    accessType: "ops team",
    month: "May",
    approvedInvoice: 564,
    rejectInvoice: 130,
    pendingInvoice: 80,
  },
  {
    notesType: [],
    accessType: "ops team",
    month: "June",
    approvedInvoice: 566,
    rejectInvoice: 140,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "ops team",
    month: "July",
    approvedInvoice: 766,
    rejectInvoice: 140,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "ops team",
    month: "August",
    approvedInvoice: 765,
    rejectInvoice: 46,
    pendingInvoice: 85,
  },
  {
    notesType: [],
    accessType: "ops team",
    month: "September",
    approvedInvoice: 67,
    rejectInvoice: 456,
    pendingInvoice: 85,
  },
];

export const reportData: ReportItem[] = [
  {
    id: 1,
    gst: "HCSIPLDL20241234",
    services: "Approved",
    location: "Maharastra",
    siteName: "30-Aug-2024",
    connectivity: "Gondia-Tx STN Andheri (Mumbai)",
    usiCode: "KJHV-7899",
    baseAmount: 15000,
    totalAmount: 15000,
    accessType: "invoice",
    priority: "",
    comment: "Sample comment for invoice 1",
  },
  {
    id: 2,
    gst: "HCSIPLDL20241234",
    services: "Approved",
    location: "Maharastra",
    siteName: "30-Aug-2024",
    connectivity: "Aurangabad-Goa",
    usiCode: "KJHV-7899",
    baseAmount: 15000,
    totalAmount: 15000,
    accessType: "invoice",
    priority: "",
    comment: "Sample comment for invoice 1",
  },
  {
    id: 3,
    gst: "HCSIPLDL20241234",
    services: "Approved",
    location: "Maharastra",
    siteName: "30-Aug-2024",
    connectivity: "Aurangabad-Gondia",
    usiCode: "KJHV-7899",
    baseAmount: 15000,
    totalAmount: 15000,
    accessType: "invoice",
    priority: "",
    comment: "Sample comment for invoice 1",
  },
  {
    id: 4,
    gst: "HCSIPLDL20241234",
    services: "Approved",
    location: "Maharastra",
    siteName: "30-Aug-2024",
    connectivity: "Ahmedabad-Goa",
    usiCode: "KJHV-7899",
    baseAmount: 15000,
    totalAmount: 15000,
    accessType: "invoice",
    priority: "",
    comment: "Sample comment for invoice 1",
  },
  {
    id: 5,
    gst: "HCSIPLDL20241234",
    services: "Approved",
    location: "Maharastra",
    siteName: "30-Aug-2024",
    connectivity: "Chennai-Mumbai",
    usiCode: "KJHV-7899",
    baseAmount: 15000,
    totalAmount: 15000,
    accessType: "invoice",
    priority: "",
    comment: "Sample comment for invoice 1",
  },
  {
    id: 6,
    gst: "HCSIPLDL20241234",
    services: "Approved",
    location: "Maharastra",
    siteName: "30-Aug-2024",
    connectivity: "Surat-Patna",
    usiCode: "KJHV-7899",
    baseAmount: 15000,
    totalAmount: 15000,
    accessType: "invoice",
    priority: "",
    comment: "Sample comment for invoice 1",
  },
  {
    id: 7,
    gst: "HCSIPLDL20241234",
    services: "Approved",
    location: "Maharastra",
    siteName: "30-Aug-2024",
    connectivity: "Gondia-Tx STN Andheri (Mumbai)",
    usiCode: "KJHV-7899",
    baseAmount: 15000,
    totalAmount: 15000,
    accessType: "invoice",
    priority: "",
    comment: "Sample comment for invoice 1",
  },
];

export const debitCreditNoteData: DebitCreditNoteDataType[] = [
  {
    id: 1,
    uniqueNumber: "INV-2024-0000031",
    billTo: "ABC pvt. ltd.",
    supplierDetails: "ABC pvt. ltd.",
    gstinOfSupplier: "12345678901234",
    state: "Maharastra",
    placeOfSupply: "Maharastra",
    gstinOfRecipient: "12345678901234",
    creditNoteNumber: "12345678901234",
    date: "06-Sep-24",
    referenceInvoiceNumber: "12345678901234",
    referenceInvoiceDate: "06-Sep-24",
    irnNumber: "12345678901234",
    agreementNumber: "12345678901234",
    agreementDate: "06-Sep-24",
    grandTotalTaxableAmount: 11500,
    grandTotalCentralTax: 11500,
    grandTotalStateUnionTerritoryTax: 11500,
    grandTotalAmount: 11500,
    amountInWords: "One Thousand One Hundred Fifty",
    note: "Sample comment for Credit Note",
    bankName: "SBI",
    beneficiaryAcNo: "12345678901234",
    beneficiaryAcName: "ABC pvt. ltd.",
    ifsc: "SBI00001",
    pan: "ABCDE1234F",
    paymentTerms: "06-Sep-24",
    status: "Approved",
    type: "Credit Note",
    createdOn: "06-Sep-24",
    createdBy: "Sunil Kumar",
  },
  {
    id: 2,
    uniqueNumber: "INV-2024-0000032",
    billTo: "ABC pvt. ltd.",
    supplierDetails: "ABC pvt. ltd.",
    gstinOfSupplier: "12345678901234",
    state: "Maharastra",
    placeOfSupply: "Maharastra",
    gstinOfRecipient: "12345678901234",
    creditNoteNumber: "12345678901234",
    date: "06-Sep-24",
    referenceInvoiceNumber: "12345678901234",
    referenceInvoiceDate: "06-Sep-24",
    irnNumber: "12345678901234",
    agreementNumber: "12345678901234",
    agreementDate: "06-Sep-24",
    grandTotalTaxableAmount: 11500,
    grandTotalCentralTax: 11500,
    grandTotalStateUnionTerritoryTax: 11500,
    grandTotalAmount: 11500,
    amountInWords: "One Thousand One Hundred Fifty",
    note: "Sample comment for Credit Note",
    bankName: "SBI",
    beneficiaryAcNo: "12345678901234",
    beneficiaryAcName: "ABC pvt. ltd.",
    ifsc: "SBI00001",
    pan: "ABCDE1234F",
    paymentTerms: "06-Sep-24",
    status: "Pending",
    type: "Debit Note",
    createdOn: "06-Sep-24",
    createdBy: "Sunil Kumar",
  },
  {
    id: 3,
    uniqueNumber: "INV-2024-0000033",
    billTo: "ABC pvt. ltd.",
    supplierDetails: "ABC pvt. ltd.",
    gstinOfSupplier: "12345678901234",
    state: "Maharastra",
    placeOfSupply: "Maharastra",
    gstinOfRecipient: "12345678901234",
    creditNoteNumber: "12345678901234",
    date: "06-Sep-24",
    referenceInvoiceNumber: "12345678901234",
    referenceInvoiceDate: "06-Sep-24",
    irnNumber: "12345678901234",
    agreementNumber: "12345678901234",
    agreementDate: "06-Sep-24",
    grandTotalTaxableAmount: 11500,
    grandTotalCentralTax: 11500,
    grandTotalStateUnionTerritoryTax: 11500,
    grandTotalAmount: 11500,
    amountInWords: "One Thousand One Hundred Fifty",
    note: "Sample comment for Credit Note",
    bankName: "SBI",
    beneficiaryAcNo: "12345678901234",
    beneficiaryAcName: "ABC pvt. ltd.",
    ifsc: "SBI00001",
    pan: "ABCDE1234F",
    paymentTerms: "06-Sep-24",
    status: "Rejected",
    type: "Credit Note",
    createdOn: "06-Sep-24",
    createdBy: "Sunil Kumar",
  },
  {
    id: 4,
    uniqueNumber: "INV-2024-0000034",
    billTo: "ABC pvt. ltd.",
    supplierDetails: "ABC pvt. ltd.",
    gstinOfSupplier: "12345678901234",
    state: "Maharastra",
    placeOfSupply: "Maharastra",
    gstinOfRecipient: "12345678901234",
    creditNoteNumber: "12345678901234",
    date: "06-Sep-24",
    referenceInvoiceNumber: "12345678901234",
    referenceInvoiceDate: "06-Sep-24",
    irnNumber: "12345678901234",
    agreementNumber: "12345678901234",
    agreementDate: "06-Sep-24",
    grandTotalTaxableAmount: 11500,
    grandTotalCentralTax: 11500,
    grandTotalStateUnionTerritoryTax: 11500,
    grandTotalAmount: 11500,
    amountInWords: "One Thousand One Hundred Fifty",
    note: "Sample comment for Credit Note",
    bankName: "SBI",
    beneficiaryAcNo: "12345678901234",
    beneficiaryAcName: "ABC pvt. ltd.",
    ifsc: "SBI00001",
    pan: "ABCDE1234F",
    paymentTerms: "06-Sep-24",
    status: "Rejected",
    type: "Credit Note",
    createdOn: "06-Sep-24",
    createdBy: "Sunil Kumar",
  },
];

export const indianStates: StateData[] = [
  { value: "all", label: "All", sitesName: [] },
  { value: "Andhra Pradesh", label: "Andhra Pradesh", sitesName: [] },
  {
    value: "Arunachal Pradesh",
    label: "Arunachal Pradesh",
    sitesName: [
      {
        value: "Site 1 Arunachal Pradesh",
        label: "Site 1 Arunachal Pradesh",
        buyerGstin: "06AAHCB6924G1ZP",
        buyerLocation: "Itanagar",
      },
      {
        value: "Site 2 Arunachal Pradesh",
        label: "Site 2 Arunachal Pradesh",
        buyerGstin: "06AAHCB6924G1ZR",
        buyerLocation: "Tezu",
      },
    ],
  },
  { value: "Assam", label: "Assam", sitesName: [] },
  { value: "Bihar", label: "Bihar", sitesName: [] },
  { value: "Chhattisgarh", label: "Chhattisgarh", sitesName: [] },
  { value: "Goa", label: "Goa", sitesName: [] },
  { value: "Gujarat", label: "Gujarat", sitesName: [] },
  { value: "Haryana", label: "Haryana", sitesName: [] },
  { value: "Himachal Pradesh", label: "Himachal Pradesh", sitesName: [] },
  { value: "Jharkhand", label: "Jharkhand", sitesName: [] },
  { value: "Karnataka", label: "Karnataka", sitesName: [] },
  { value: "Kerala", label: "Kerala", sitesName: [] },
  { value: "Madhya Pradesh", label: "Madhya Pradesh", sitesName: [] },
  { value: "Maharashtra", label: "Maharashtra", sitesName: [] },
  { value: "Manipur", label: "Manipur", sitesName: [] },
  { value: "Meghalaya", label: "Meghalaya", sitesName: [] },
  { value: "Mizoram", label: "Mizoram", sitesName: [] },
  { value: "Nagaland", label: "Nagaland", sitesName: [] },
  { value: "Odisha", label: "Odisha", sitesName: [] },
  { value: "Punjab", label: "Punjab", sitesName: [] },
  { value: "Rajasthan", label: "Rajasthan", sitesName: [] },
  { value: "Sikkim", label: "Sikkim", sitesName: [] },
  { value: "Tamil Nadu", label: "Tamil Nadu", sitesName: [] },
  { value: "Telangana", label: "Telangana", sitesName: [] },
  { value: "Tripura", label: "Tripura", sitesName: [] },
  { value: "Uttar Pradesh", label: "Uttar Pradesh", sitesName: [] },
  { value: "Uttarakhand", label: "Uttarakhand", sitesName: [] },
  { value: "West Bengal", label: "West Bengal", sitesName: [] },
  {
    value: "Andaman and Nicobar Islands",
    label: "Andaman and Nicobar Islands",
    sitesName: [],
  },
  { value: "Chandigarh", label: "Chandigarh", sitesName: [] },
  {
    value: "Dadra and Nagar Haveli and Daman and Diu",
    label: "Dadra and Nagar Haveli and Daman and Diu",
    sitesName: [],
  },
  { value: "Delhi", label: "Delhi", sitesName: [] },
  { value: "Jammu and Kashmir", label: "Jammu and Kashmir", sitesName: [] },
  { value: "Ladakh", label: "Ladakh", sitesName: [] },
  { value: "Lakshadweep", label: "Lakshadweep", sitesName: [] },
  { value: "Puducherry", label: "Puducherry", sitesName: [] },
];

export const commentMatrix: commentMatrixDataType[] = [
  {
    id: 1,
    comment:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    createdBy: "rohan.kumar",
    createdOn: "30-Aug-2024 12:43 PM",
    action: "Approved",
  },
  {
    id: 2,
    comment:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    createdBy: "rohan.kumar",
    createdOn: "30-Aug-2024 11:20 AM",
    action: "Approved",
  },
  {
    id: 3,
    comment:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    createdBy: "rohan.kumar",
    createdOn: "30-Aug-2024 10:00 AM",
    action: "Query Raised",
  },
  {
    id: 4,
    comment:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    createdBy: "rohan.kumar",
    createdOn: "30-Aug-2024 09:00 AM",
    action: "Rejected",
  },
  {
    id: 5,
    comment:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    createdBy: "rohan.kumar",
    createdOn: "30-Aug-2024 08:00 AM",
    action: "Approved",
  },
  {
    id: 6,
    comment:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    createdBy: "rohan.kumar",
    createdOn: "30-Aug-2024 01:00 PM",
    action: "Approved",
  },
];

export const ServiceInventoryLData: ServiceInventoryLDataType[] = [
  {
    id: 1,
    serviceClass: "AFTN/DSC 64",
    bandwidth: 64,
    usiCode: "AAIH-AS-001001",
    serviceType: "AFTN/DSC",
    superCededUsi: "",
    fromSite: "Delhi",
    fromSiteNo: 1,
    toSite: "Mumbai",
    toSiteNo: 20,
    connectivity: "Delhi-Kolkata",
    fromSiteInterface: "V.35",
    layer2: "Serial",
    toSiteInterface: "V.35",
    fromSiteLID: "VIDP",
    fromSiteFAC: "ATCT",
    toSiteLID: "VABB",
    toSiteFAC: "ATCT",
    rmaCode: 3,
    phase: "Phase 1",
    miscInfo: "New Svc Type: N / Campus Cable: N",
    startDate: "20-Feb-2020",
    endDate: "31-Mar-2034",
    activeNonActive: "Active",
    remarks: "In scope",
    oct23: "Yes",
    nov23: "Yes",
    dec23: "Yes",
    jan23: "Yes",
    feb23: "Yes",
    mar23: "Yes",
    apr23: "Yes",
    may23: "Yes",
    jun23: "Yes",
  },
  {
    id: 2,
    serviceClass: "AFTN/DSC 128",
    bandwidth: 128,
    usiCode: "BBIH-AS-002002",
    serviceType: "AFTN/DSC",
    superCededUsi: "",
    fromSite: "Chennai",
    fromSiteNo: 2,
    toSite: "Bangalore",
    toSiteNo: 21,
    connectivity: "Chennai-Hyderabad",
    fromSiteInterface: "V.35",
    layer2: "Serial",
    toSiteInterface: "V.35",
    fromSiteLID: "VOMM",
    fromSiteFAC: "ATCT",
    toSiteLID: "VOBG",
    toSiteFAC: "ATCT",
    rmaCode: 4,
    phase: "Phase 2",
    miscInfo: "New Svc Type: Y / Campus Cable: N",
    startDate: "15-Mar-2021",
    endDate: "30-Apr-2035",
    activeNonActive: "Active",
    remarks: "In scope",
    oct23: "Yes",
    nov23: "Yes",
    dec23: "Yes",
    jan23: "Yes",
    feb23: "Yes",
    mar23: "Yes",
    apr23: "Yes",
    may23: "Yes",
    jun23: "Yes",
  },
  {
    id: 3,
    serviceClass: "AFTN/DSC 256",
    bandwidth: 256,
    usiCode: "CCIH-AS-003003",
    serviceType: "AFTN/DSC",
    superCededUsi: "",
    fromSite: "Hyderabad",
    fromSiteNo: 3,
    toSite: "Pune",
    toSiteNo: 22,
    connectivity: "Hyderabad-Chennai",
    fromSiteInterface: "V.35",
    layer2: "Serial",
    toSiteInterface: "V.35",
    fromSiteLID: "VOHS",
    fromSiteFAC: "ATCT",
    toSiteLID: "VAPO",
    toSiteFAC: "ATCT",
    rmaCode: 5,
    phase: "Phase 3",
    miscInfo: "New Svc Type: N / Campus Cable: Y",
    startDate: "10-Apr-2022",
    endDate: "20-May-2036",
    activeNonActive: "Active",
    remarks: "In scope",
    oct23: "Yes",
    nov23: "Yes",
    dec23: "Yes",
    jan23: "Yes",
    feb23: "Yes",
    mar23: "Yes",
    apr23: "Yes",
    may23: "Yes",
    jun23: "Yes",
  },
  {
    id: 4,
    serviceClass: "AFTN/DSC 512",
    bandwidth: 512,
    usiCode: "DDIH-AS-004004",
    serviceType: "AFTN/DSC",
    superCededUsi: "",
    fromSite: "Kolkata",
    fromSiteNo: 4,
    toSite: "Ahmedabad",
    toSiteNo: 23,
    connectivity: "Kolkata-Mumbai",
    fromSiteInterface: "V.35",
    layer2: "Serial",
    toSiteInterface: "V.35",
    fromSiteLID: "VECC",
    fromSiteFAC: "ATCT",
    toSiteLID: "VAAH",
    toSiteFAC: "ATCT",
    rmaCode: 6,
    phase: "Phase 4",
    miscInfo: "New Svc Type: Y / Campus Cable: N",
    startDate: "25-May-2023",
    endDate: "30-Jun-2037",
    activeNonActive: "Active",
    remarks: "In scope",
    oct23: "Yes",
    nov23: "Yes",
    dec23: "Yes",
    jan23: "Yes",
    feb23: "Yes",
    mar23: "Yes",
    apr23: "Yes",
    may23: "Yes",
    jun23: "Yes",
  },
  {
    id: 5,
    serviceClass: "AFTN/DSC 1024",
    bandwidth: 1024,
    usiCode: "EEIH-AS-005005",
    serviceType: "AFTN/DSC",
    superCededUsi: "",
    fromSite: "Jaipur",
    fromSiteNo: 5,
    toSite: "Lucknow",
    toSiteNo: 24,
    connectivity: "Jaipur-Delhi",
    fromSiteInterface: "V.35",
    layer2: "Serial",
    toSiteInterface: "V.35",
    fromSiteLID: "VIJP",
    fromSiteFAC: "ATCT",
    toSiteLID: "VILK",
    toSiteFAC: "ATCT",
    rmaCode: 7,
    phase: "Phase 5",
    miscInfo: "New Svc Type: N / Campus Cable: Y",
    startDate: "10-Jun-2024",
    endDate: "15-Jul-2038",
    activeNonActive: "Active",
    remarks: "In scope",
    oct23: "Yes",
    nov23: "Yes",
    dec23: "Yes",
    jan23: "Yes",
    feb23: "Yes",
    mar23: "Yes",
    apr23: "Yes",
    may23: "Yes",
    jun23: "Yes",
  },
  {
    id: 6,
    serviceClass: "AFTN/DSC 2048",
    bandwidth: 2048,
    usiCode: "FFIH-AS-006006",
    serviceType: "AFTN/DSC",
    superCededUsi: "",
    fromSite: "Goa",
    fromSiteNo: 6,
    toSite: "Nagpur",
    toSiteNo: 25,
    connectivity: "Goa-Mumbai",
    fromSiteInterface: "V.35",
    layer2: "Serial",
    toSiteInterface: "V.35",
    fromSiteLID: "VOGO",
    fromSiteFAC: "ATCT",
    toSiteLID: "VANP",
    toSiteFAC: "ATCT",
    rmaCode: 8,
    phase: "Phase 6",
    miscInfo: "New Svc Type: Y / Campus Cable: N",
    startDate: "20-Jul-2025",
    endDate: "25-Aug-2039",
    activeNonActive: "Active",
    remarks: "In scope",
    oct23: "Yes",
    nov23: "Yes",
    dec23: "Yes",
    jan23: "Yes",
    feb23: "Yes",
    mar23: "Yes",
    apr23: "Yes",
    may23: "Yes",
    jun23: "Yes",
  },
  {
    id: 7,
    serviceClass: "AFTN/DSC 4096",
    bandwidth: 4096,
    usiCode: "GGIH-AS-007007",
    serviceType: "AFTN/DSC",
    superCededUsi: "",
    fromSite: "Patna",
    fromSiteNo: 7,
    toSite: "Bhubaneswar",
    toSiteNo: 26,
    connectivity: "Patna-Kolkata",
    fromSiteInterface: "V.35",
    layer2: "Serial",
    toSiteInterface: "V.35",
    fromSiteLID: "VEPT",
    fromSiteFAC: "ATCT",
    toSiteLID: "VEBS",
    toSiteFAC: "ATCT",
    rmaCode: 9,
    phase: "Phase 7",
    miscInfo: "New Svc Type: N / Campus Cable: Y",
    startDate: "15-Aug-2026",
    endDate: "20-Sep-2040",
    activeNonActive: "Active",
    remarks: "In scope",
    oct23: "Yes",
    nov23: "Yes",
    dec23: "Yes",
    jan23: "Yes",
    feb23: "Yes",
    mar23: "Yes",
    apr23: "Yes",
    may23: "Yes",
    jun23: "Yes",
  },
  {
    id: 8,
    serviceClass: "AFTN/DSC 8192",
    bandwidth: 8192,
    usiCode: "HHIH-AS-008008",
    serviceType: "AFTN/DSC",
    superCededUsi: "",
    fromSite: "Trivandrum",
    fromSiteNo: 8,
    toSite: "Cochin",
    toSiteNo: 27,
    connectivity: "Trivandrum-Chennai",
    fromSiteInterface: "V.35",
    layer2: "Serial",
    toSiteInterface: "V.35",
    fromSiteLID: "VOTV",
    fromSiteFAC: "ATCT",
    toSiteLID: "VOCC",
    toSiteFAC: "ATCT",
    rmaCode: 10,
    phase: "Phase 8",
    miscInfo: "New Svc Type: Y / Campus Cable: N",
    startDate: "10-Sep-2027",
    endDate: "15-Oct-2041",
    activeNonActive: "Active",
    remarks: "In scope",
    oct23: "Yes",
    nov23: "Yes",
    dec23: "Yes",
    jan23: "Yes",
    feb23: "Yes",
    mar23: "Yes",
    apr23: "Yes",
    may23: "Yes",
    jun23: "Yes",
  },
];

export const ServiceInventoryCData: ServiceInventoryCDataType[] = [
  {
    id: 1,
    serviceClass: "AFTN/DSC 64",
    usiCode: "AAIH-AS-001001",
    fromSite: "Delhi",
    toSite: "Mumbai",
    phase: "Phase 1",
    startDate: "24-Aug-2024",
    endDate: "---",
    status: "Active",
  },
  {
    id: 2,
    serviceClass: "AFTN/DSC 65",
    usiCode: "AAIH-AS-001002",
    fromSite: "Delhi",
    toSite: "Mumbai",
    phase: "Phase 1",
    startDate: "27-Aug-2024",
    endDate: "30-Aug-2025",
    status: "Inactive",
  },
  {
    id: 3,
    serviceClass: "AFTN/DSC 66",
    usiCode: "AAIH-AS-001003",
    fromSite: "Delhi",
    toSite: "Mumbai",
    phase: "Phase 1",
    startDate: "24-Aug-2024",
    endDate: "---",
    status: "Active",
  },
  {
    id: 4,
    serviceClass: "AFTN/DSC 67",
    usiCode: "AAIH-AS-001004",
    fromSite: "Delhi",
    toSite: "Mumbai",
    phase: "Phase 1",
    startDate: "25-Aug-2024",
    endDate: "16-Sep-2024",
    status: "Inactive",
  },
];

export const PricingSheetData: PricingSheetDataType[] = [
  {
    id: 1,
    serviceClass: "AFTN/DSC 64",
    usiCode: "AAIH-AS-001001",
    fromSite: "Delhi",
    toSite: "Mumbai",
    phase: "Phase 1",
    startDate: "24-Aug-2024",
    status: "Active",
  },
  {
    id: 2,
    serviceClass: "AFTN/DSC 65",
    usiCode: "AAIH-AS-001002",
    fromSite: "Delhi",
    toSite: "Mumbai",
    phase: "Phase 1",
    startDate: "27-Aug-2024",
    status: "Active",
  },
  {
    id: 3,
    serviceClass: "AFTN/DSC 66",
    usiCode: "AAIH-AS-001003",
    fromSite: "Delhi",
    toSite: "Mumbai",
    phase: "Phase 1",
    startDate: "24-Aug-2024",
    status: "Active",
  },
  {
    id: 4,
    serviceClass: "AFTN/DSC 67",
    usiCode: "AAIH-AS-001004",
    fromSite: "Delhi",
    toSite: "Mumbai",
    phase: "Phase 1",
    startDate: "25-Aug-2024",
    status: "Active",
  },
];

export const LineItemData: LineItemDataType[] = [
  {
    id: 1,
    usiCode: "AAIH-IP-001031",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 2,
    usiCode: "AAIH-IP-001032",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "DSC 12",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 3,
    usiCode: "AAIH-IP-001033",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "RADAR DATA 128",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "29-03-2023",
    billingEndPeriod: "12-04-2024",
    hsnCode: "567565",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 4,
    usiCode: "AAIH-IP-001034",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "AFTN 9.6",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 5,
    usiCode: "AAIH-IP-001035",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "ADS - B 128",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 6,
    usiCode: "AAIH-IP-001036",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "AFTN/DSC 64",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 7,
    usiCode: "AAIH-IP-001037",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "RCAG 64",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 8,
    usiCode: "AAIH-IP-001038",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 9,
    usiCode: "AAIH-IP-001039",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "RADAR DATA 128",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 10,
    usiCode: "AAIH-IP-001010",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 11,
    usiCode: "AAIH-IP-001011",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "ADS - B 128",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 12,
    usiCode: "AAIH-IP-001012",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 13,
    usiCode: "AAIH-IP-001013",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 14,
    usiCode: "AAIH-IP-001014",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "RADAR DATA 128",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 15,
    usiCode: "AAIH-IP-001015",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "ADS - B 128",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 16,
    usiCode: "AAIH-IP-001016",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "DSC 128",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 17,
    usiCode: "AAIH-IP-001017",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 18,
    usiCode: "AAIH-IP-001018",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 19,
    usiCode: "AAIH-IP-001019",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "GAGAN 128",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "435645",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 20,
    usiCode: "AAIH-IP-001020",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "AFTN 9.6",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 21,
    usiCode: "AAIH-IP-001021",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 22,
    usiCode: "AAIH-IP-001022",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 23,
    usiCode: "AAIH-IP-001023",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 24,
    usiCode: "AAIH-IP-001024",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 25,
    usiCode: "AAIH-IP-001025",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 26,
    usiCode: "AAIH-IP-001026",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 27,
    usiCode: "AAIH-IP-001027",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 28,
    usiCode: "AAIH-IP-001028",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 29,
    usiCode: "AAIH-IP-001029",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 30,
    usiCode: "AAIH-IP-001030",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 31,
    usiCode: "AAIH-IP-0010331",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 32,
    usiCode: "AAIH-IP-0010332",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 33,
    usiCode: "AAIH-IP-0010333",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
  {
    id: 34,
    usiCode: "AAIH-IP-0010334",
    connectivity: "Delhi-Kolkata",
    stateName: "New Delhi",
    service: "IP Pipe 2048",
    descriptionOfService: "Value added Service Charges",
    billingStartPeriod: "28-03-2023",
    billingEndPeriod: "31-03-2023",
    hsnCode: "998399",
    quantity: 4,
    unitPrice: 154.33,
    totalAmount: 617.32,
    taxableAmount: 617.32,
    centralTax: null,
    centralTaxValue: null,
    integratedTax: 18,
    integratedTaxValue: 111.12,
    stateUnionTerritoryTax: null,
    stateUnionTerritoryTaxValue: null,
    totalAmountIncTax: 728.44,
  },
];

export const serviceType: serviceTypeDataType[] = [
  { value: "ADS-B 128", label: "ADS-B 128" },
  { value: "AFTN 9.6", label: "AFTN 9.6" },
  { value: "AFTN/DATIS 64", label: "AFTN/DATIS 64" },
  { value: "AFTN/DSC 64", label: "AFTN/DSC 64" },
  { value: "DATIS 64", label: "DATIS 64" },
  { value: "DSC 12", label: "DSC 12" },
  { value: "GAGAN 128", label: "GAGAN 128" },
  { value: "RADAR DATA 128", label: "RADAR DATA 128" },
  { value: "RCAG 64", label: "RCAG 64" },
  { value: "SELCAL 64", label: "SELCAL 64" },
  { value: "SPEECH 64", label: "SPEECH 64" },
  { value: "Speech/VCCS 2048", label: "Speech/VCCS 2048" },
  { value: "DATA 4096", label: "DATA 4096" },
  { value: "RADAR Display 512", label: "RADAR Display 512" },
  { value: "AFTN/DSC 128", label: "AFTN/DSC 128" },
  { value: "ATFM 2048", label: "ATFM 2048" },
  { value: "IP Pipe 2048", label: "IP Pipe 2048" },
  { value: "IP Pipe 3072", label: "IP Pipe 3072" },
  { value: "DSC ARD 64", label: "DSC ARD 64" },
  { value: "IP Pipe 512", label: "IP Pipe 512" },
  { value: "RADAR 128", label: "RADAR 128" },
];

export const siteData: siteDataType[] = [
  {
    id: 1,
    siteName: "Delhi",
    siteId: "1",
    value: "Delhi",
    label: "Delhi",
  },
  {
    id: 2,
    siteName: "Rashtrapati Bhawan (RASAM)",
    siteId: "2",
    value: "Rashtrapati Bhawan (RASAM)",
    label: "Rashtrapati Bhawan (RASAM)",
  },
  {
    id: 3,
    siteName: "CHQ",
    siteId: "3",
    value: "CHQ",
    label: "CHQ",
  },
  {
    id: 4,
    siteName: "Safdarjung",
    siteId: "4",
    value: "Safdarjung",
    label: "Safdarjung",
  },
  {
    id: 5,
    siteName: "DGCA",
    siteId: "5",
    value: "DGCA",
    label: "DGCA",
  },
  {
    id: 6,
    siteName: "Jaipur",
    siteId: "6",
    value: "Jaipur",
    label: "Jaipur",
  },
  {
    id: 7,
    siteName: "Lucknow",
    siteId: "7",
    value: "Lucknow",
    label: "Lucknow",
  },
  {
    id: 8,
    siteName: "Varanasi",
    siteId: "8",
    value: "Varanasi",
    label: "Varanasi",
  },
  {
    id: 9,
    siteName: "Khajuraho",
    siteId: "9",
    value: "Khajuraho",
    label: "Khajuraho",
  },
  {
    id: 10,
    siteName: "Bhunter",
    siteId: "10",
    value: "Bhunter",
    label: "Bhunter",
  },
  {
    id: 11,
    siteName: "Dehradun",
    siteId: "11",
    value: "Dehradun",
    label: "Dehradun",
  },
  {
    id: 12,
    siteName: "Mumbai",
    siteId: "12",
    value: "Mumbai",
    label: "Mumbai",
  },
  {
    id: 13,
    siteName: "Ahmedabad",
    siteId: "13",
    value: "Ahmedabad",
    label: "Ahmedabad",
  },
  {
    id: 14,
    siteName: "Guwahati",
    siteId: "14",
    value: "Guwahati",
    label: "Guwahati",
  },
  {
    id: 15,
    siteName: "Kolkata",
    siteId: "15",
    value: "Kolkata",
    label: "Kolkata",
  },
  {
    id: 16,
    siteName: "Amritsar",
    siteId: "16",
    value: "Amritsar",
    label: "Amritsar",
  },
  {
    id: 17,
    siteName: "Vizag",
    siteId: "17",
    value: "Vizag",
    label: "Vizag",
  },
  {
    id: 18,
    siteName: "Aurngabad",
    siteId: "18",
    value: "Aurngabad",
    label: "Aurngabad",
  },
];

export const stateMasterData: StateMasterDataType[] = [
  {
    id: 1,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Andhra Pradesh",
  },
  {
    id: 2,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Arunachal Pradesh",
  },
  {
    id: 3,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Assam",
  },
  {
    id: 4,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Bihar",
  },
  {
    id: 5,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Chhattisgarh",
  },
  {
    id: 6,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Goa",
  },
  {
    id: 7,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Gujarat",
  },
  {
    id: 8,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Haryana",
  },
  {
    id: 9,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Himachal Pradesh",
  },
  {
    id: 10,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Jharkhand",
  },
  {
    id: 11,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Karnataka",
  },
  {
    id: 12,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Kerala",
  },
  {
    id: 13,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Madhya Pradesh",
  },
  {
    id: 14,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Maharashtra",
  },
  {
    id: 15,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Manipur",
  },
  {
    id: 16,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Meghalaya",
  },
  {
    id: 17,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Mizoram",
  },
  {
    id: 18,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Nagaland",
  },
  {
    id: 19,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Odisha",
  },
  {
    id: 20,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Punjab",
  },
  {
    id: 21,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Rajasthan",
  },
  {
    id: 22,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Sikkim",
  },
  {
    id: 23,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Tamil Nadu",
  },
  {
    id: 24,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Telangana",
  },
  {
    id: 25,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Tripura",
  },
  {
    id: 26,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Uttar Pradesh",
  },
  {
    id: 27,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Uttarakhand",
  },
  {
    id: 28,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "West Bengal",
  },
  {
    id: 29,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Andaman and Nicobar Islands",
  },
  {
    id: 30,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Chandigarh",
  },
  {
    id: 31,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Dadra and Nagar Haveli and Daman and Diu",
  },
  {
    id: 32,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Delhi",
  },
  {
    id: 33,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Jammu and Kashmir",
  },
  {
    id: 34,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Ladakh",
  },
  {
    id: 35,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Lakshadweep",
  },
  {
    id: 36,
    createdBy: "admin",
    createdOn: "26-Sep-2024",
    stateName: "Puducherry",
  },
];

export const FinancialBid: FinancialBidDataType[] = [
  {
    id: 1,
    connectivity: "Varanasi-patna",
    service: "AFTN/DSC 64",
    usiCode: "AAIH-AS-008004",
    valueAddedServiceCharge: 17713,
    accessServiceChargeRma2Rma3: 895552,
    accessServiceChargeRma1: 0,
    totalMediaCharge: 107265,
    mediaManagementCharge: 9653,
    noccAndSoccCharge: 617463,
    interfaceProtocolCharge: 34804,
    fixedSiteCharge: 1396963,
    totalChargeForService: 2166150,
    dailyCharges: 5934,
    phase: "Phase 7",
    dateOfImpOfService: "10-Sep-2024",
    noOfDaysServiceIsActiveInYear: 182,
    noOfDaysInFirstQuat: 0,
    costOfServiceInFirstQuat: 0,
    noOfDaysInSecondQuat: 0,
    costOfServiceInSecondQuat: 0,
    noOfDaysInThirdQuat: 92,
    costOfServiceInThirdQuat: 545988,
    noOfDaysInFourthQuat: 90,
    costOfServiceInFourthQuat: 534119,
    totalCostOfService: 1080108,
  },
  {
    id: 2,
    connectivity: "Varanasi-Jharsuguda",
    service: "AFTN/DSC 64",
    usiCode: "AAIH-AS-008004",
    valueAddedServiceCharge: 17713,
    accessServiceChargeRma2Rma3: 895552,
    accessServiceChargeRma1: 0,
    totalMediaCharge: 107265,
    mediaManagementCharge: 9653,
    noccAndSoccCharge: 617463,
    interfaceProtocolCharge: 34804,
    fixedSiteCharge: 1396963,
    totalChargeForService: 2166150,
    dailyCharges: 5934,
    phase: "Phase 7",
    dateOfImpOfService: "10-Sep-2024",
    noOfDaysServiceIsActiveInYear: 182,
    noOfDaysInFirstQuat: 0,
    costOfServiceInFirstQuat: 0,
    noOfDaysInSecondQuat: 0,
    costOfServiceInSecondQuat: 0,
    noOfDaysInThirdQuat: 92,
    costOfServiceInThirdQuat: 545988,
    noOfDaysInFourthQuat: 90,
    costOfServiceInFourthQuat: 534119,
    totalCostOfService: 1080108,
  },
  {
    id: 3,
    connectivity: "Varanasi-Kathihar",
    service: "AFTN/DSC 64",
    usiCode: "AAIH-AS-008004",
    valueAddedServiceCharge: 17713,
    accessServiceChargeRma2Rma3: 895552,
    accessServiceChargeRma1: 0,
    totalMediaCharge: 107265,
    mediaManagementCharge: 9653,
    noccAndSoccCharge: 617463,
    interfaceProtocolCharge: 34804,
    fixedSiteCharge: 1396963,
    totalChargeForService: 2166150,
    dailyCharges: 5934,
    phase: "Phase 7",
    dateOfImpOfService: "10-Sep-2024",
    noOfDaysServiceIsActiveInYear: 182,
    noOfDaysInFirstQuat: 0,
    costOfServiceInFirstQuat: 0,
    noOfDaysInSecondQuat: 0,
    costOfServiceInSecondQuat: 0,
    noOfDaysInThirdQuat: 92,
    costOfServiceInThirdQuat: 545988,
    noOfDaysInFourthQuat: 90,
    costOfServiceInFourthQuat: 534119,
    totalCostOfService: 1080108,
  },
  {
    id: 4,
    connectivity: "Varanasi-Khajuraho",
    service: "AFTN/DSC 64",
    usiCode: "AAIH-AS-008004",
    valueAddedServiceCharge: 17713,
    accessServiceChargeRma2Rma3: 895552,
    accessServiceChargeRma1: 0,
    totalMediaCharge: 107265,
    mediaManagementCharge: 9653,
    noccAndSoccCharge: 617463,
    interfaceProtocolCharge: 34804,
    fixedSiteCharge: 1396963,
    totalChargeForService: 2166150,
    dailyCharges: 5934,
    phase: "Phase 7",
    dateOfImpOfService: "10-Sep-2024",
    noOfDaysServiceIsActiveInYear: 182,
    noOfDaysInFirstQuat: 0,
    costOfServiceInFirstQuat: 0,
    noOfDaysInSecondQuat: 0,
    costOfServiceInSecondQuat: 0,
    noOfDaysInThirdQuat: 92,
    costOfServiceInThirdQuat: 545988,
    noOfDaysInFourthQuat: 90,
    costOfServiceInFourthQuat: 534119,
    totalCostOfService: 1080108,
  },
  {
    id: 5,
    connectivity: "Varanasi-Lucknow",
    service: "AFTN/DSC 64",
    usiCode: "AAIH-AS-008004",
    valueAddedServiceCharge: 17713,
    accessServiceChargeRma2Rma3: 895552,
    accessServiceChargeRma1: 0,
    totalMediaCharge: 107265,
    mediaManagementCharge: 9653,
    noccAndSoccCharge: 617463,
    interfaceProtocolCharge: 34804,
    fixedSiteCharge: 1396963,
    totalChargeForService: 2166150,
    dailyCharges: 5934,
    phase: "Phase 7",
    dateOfImpOfService: "10-Sep-2024",
    noOfDaysServiceIsActiveInYear: 182,
    noOfDaysInFirstQuat: 0,
    costOfServiceInFirstQuat: 0,
    noOfDaysInSecondQuat: 0,
    costOfServiceInSecondQuat: 0,
    noOfDaysInThirdQuat: 92,
    costOfServiceInThirdQuat: 545988,
    noOfDaysInFourthQuat: 90,
    costOfServiceInFourthQuat: 534119,
    totalCostOfService: 1080108,
  },
  {
    id: 6,
    connectivity: "Varanasi-Nagpur",
    service: "AFTN/DSC 64",
    usiCode: "AAIH-AS-008004",
    valueAddedServiceCharge: 17713,
    accessServiceChargeRma2Rma3: 895552,
    accessServiceChargeRma1: 0,
    totalMediaCharge: 107265,
    mediaManagementCharge: 9653,
    noccAndSoccCharge: 617463,
    interfaceProtocolCharge: 34804,
    fixedSiteCharge: 1396963,
    totalChargeForService: 2166150,
    dailyCharges: 5934,
    phase: "Phase 7",
    dateOfImpOfService: "10-Sep-2024",
    noOfDaysServiceIsActiveInYear: 182,
    noOfDaysInFirstQuat: 0,
    costOfServiceInFirstQuat: 0,
    noOfDaysInSecondQuat: 0,
    costOfServiceInSecondQuat: 0,
    noOfDaysInThirdQuat: 92,
    costOfServiceInThirdQuat: 545988,
    noOfDaysInFourthQuat: 90,
    costOfServiceInFourthQuat: 534119,
    totalCostOfService: 1080108,
  },
  {
    id: 7,
    connectivity: "Varanasi-patna",
    service: "AFTN/DSC 64",
    usiCode: "AAIH-AS-008004",
    valueAddedServiceCharge: 17713,
    accessServiceChargeRma2Rma3: 895552,
    accessServiceChargeRma1: 0,
    totalMediaCharge: 107265,
    mediaManagementCharge: 9653,
    noccAndSoccCharge: 617463,
    interfaceProtocolCharge: 34804,
    fixedSiteCharge: 1396963,
    totalChargeForService: 2166150,
    dailyCharges: 5934,
    phase: "Phase 7",
    dateOfImpOfService: "10-Sep-2024",
    noOfDaysServiceIsActiveInYear: 182,
    noOfDaysInFirstQuat: 0,
    costOfServiceInFirstQuat: 0,
    noOfDaysInSecondQuat: 0,
    costOfServiceInSecondQuat: 0,
    noOfDaysInThirdQuat: 92,
    costOfServiceInThirdQuat: 545988,
    noOfDaysInFourthQuat: 90,
    costOfServiceInFourthQuat: 534119,
    totalCostOfService: 1080108,
  },
  {
    id: 8,
    connectivity: "Varanasi-Jharsuguda",
    service: "AFTN/DSC 64",
    usiCode: "AAIH-AS-008004",
    valueAddedServiceCharge: 17713,
    accessServiceChargeRma2Rma3: 895552,
    accessServiceChargeRma1: 0,
    totalMediaCharge: 107265,
    mediaManagementCharge: 9653,
    noccAndSoccCharge: 617463,
    interfaceProtocolCharge: 34804,
    fixedSiteCharge: 1396963,
    totalChargeForService: 2166150,
    dailyCharges: 5934,
    phase: "Phase 7",
    dateOfImpOfService: "10-Sep-2024",
    noOfDaysServiceIsActiveInYear: 182,
    noOfDaysInFirstQuat: 0,
    costOfServiceInFirstQuat: 0,
    noOfDaysInSecondQuat: 0,
    costOfServiceInSecondQuat: 0,
    noOfDaysInThirdQuat: 92,
    costOfServiceInThirdQuat: 545988,
    noOfDaysInFourthQuat: 90,
    costOfServiceInFourthQuat: 534119,
    totalCostOfService: 1080108,
  },
];

export const DownloadSLAData: DownloadSLADataType[] = [
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Pending",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Approved",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Pending",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Pending",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Approved",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Pending",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Rejected",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Pending",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Rejected",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Pending",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Pending",
    penaltyAmount: 51560.97,
  },
  {
    year: "2024",
    month: "October",
    quarter: "",
    usiCode: "AAIH-AB-042040",
    totalPenalty: "68832.24",
    rma: "4",
    availabilityTimeInMinutes: "44640",
    outageTimeInMinutes: "593.1",
    exceptionTimeOutage: "420.0",
    outageTimeHarris: "173.12",
    status: "Pending",
    penaltyAmount: 51560.97,
  },
];

export const status = {
  initiate: "initiate",
  scopeFinalized: "Scope Finalized",
  pending: "Pending",
  queryRaised: "Query Raised",
  new: "New",
  businessApprovalPending :"Business Approval Pending",
  vendorFinalized: "Vendor Finalized",
  vendorDetailsSubmitted: "Vendor Details Submitted",
  vendorRegistrationPending: "Vendor Registration Pending",
  acknowledged: "Acknowledged",
  dbPending: "D&B Pending",
  dmdApprovalPending: "DMD Approval Pending",
  tptApprovalPending: "TPT Approval Pending",
  pendingAtMRO: "Pending At MRO",
  fnaApprovalPending: "NFA Approval Pending",
  tapIDPending: "TAP ID Pending",
  signdeskReqestCreated: "Signdesk Request Created",
  vendorCodeCreated: "Vendor Code Created",
  PendingOnDBReport:'HOD Approval Pending on D&B Report',
  approved: "Approved",
  rejected: "Rejected"

};


export const subStatus = {
  initiator: "initiator",
  ackonwledgedByMRO: "Acknowledged By MRO",
  pendingAtBusiness:"Pending At Business",
  pendingAtMRO: "Pending At MRO",
  pendingAtHOD: "Pending At HOD",
  pendingAtInitiator: "Pending At Initiator",
  pendingAtMROApprover1: "Pending At MRO Approver Level 1",
  pendingAtMROApprover2: "Pending At MRO Approver Level 2",
  pendingAtDMD: "Pending At DMD",
  pendingAtFNA: "Pending At NFA",
  pendingAtSigndesk: "Pending At Signdesk",
};

export const documentTypeLabels = {
  relationshipDeclarationForm: "Relationship Declaration Form",
  vendorUndertakingForm: "Vendor Undertaking Form",
  courtCriminalRecord: "Court/Criminal Records",
  bankAccountAttachment: "Bank Account",
  gstinAttachment: "GSTIN",
  msmeAttachment: "MSME/ Declaration in case not registered under MSME",
  aadharCard: "Aadhaar Card",
  panCard: "PAN Card",
  formAspAndRelatedDocuments: "Form - ASP and related documents",
  olderPosFromOtherClients: "Any 2 Older POs From Other Clients",
  buildingAndInteriorAttachments: "4-5 Pics Of The Building And Interior",
  abacPolicy: "ABAC Policy (Or Front Page Of Document)",
  oldVendorCode: "Old Vendor Code (If Existing Partner)",
  supplierReferenceAttachment: "3 Supplier References (If Applicable)",
  clientReferenceAttachment: "3 Client References With Email And Phone",
  proofOfEstablishmentAttachment:
    "Proof Of Establishment (Valid ID Proof)",
  pfChallan: "PF Challan/List Of Employees Sample",
  cibilReport: "CIBIL Report",
  shareholdingPattern: "Shareholding Pattern",
  dinNumberAttachment: "DIN Number - Directorship Details",
  auditedFinancialStatements: "Audited Financial Statements - 3 Years",
  gstAttachments: "GST Certificate (Multiple Docs)",
  cinNumberAttachment: "Certificate Of Incorporation With CIN Number",
};
